#!/bin/bash

TREE_NAME=$1
shift

SRM_SERVICE=$1
shift

SRM_BASEPATH=$1
shift

SRM_BASE="${SRM_SERVICE}${SRM_BASEPATH}"

TREE_DIR=

for user_dir in $@; do
  LCGDIR=$SRM_BASE/user/${user_dir}/${LNuAA_ANALYSIS_DIR}/${LNuAA_ANALYSIS_REVISION}  
  if [ "$TREE_DIR" == "" ]; then
    TREE_DIR=`lcg-ls -bD srmv2 $LCGDIR | grep -m 1 ${TREE_NAME} `
  fi
done

echo $TREE_DIR
