#!/bin/bash

SRM_SERVICE="srm://srm-eoscms.cern.ch:8443/srm/v2/server?SFN="
SRM_BASEPATH="/eos/cms/store/"

proxy=${X509_USER_PROXY:-/tmp/x509up_u$UID}

logerror() {
  echo 2>&1 "$@"
}

die() {
  if [ $# -gt 0 ]; then
    logerror
    logerror "$@"
  fi
  exit 1
}

check_proxy() {
  hours=$1
  proxy=$2
  if ! [ -f "$proxy" ]; then
    logerror
    logerror "NOTE: No grid proxy found.  (Expecting to find it here: $proxy.)"
    return 1
  fi

  #Issue a warning if less than this many seconds remain:
  min_proxy_lifetime=$((3600*$hours))

  seconds_left="`voms-proxy-info --timeleft --file=$proxy 2>/dev/null`"

  if [ "$seconds_left" = "" ]; then
    echo "WARNING: cannot find time remaining for grid proxy."
    voms-proxy-info -all -path $proxy
    return 0
  fi
  if [ "$seconds_left" -lt "$min_proxy_lifetime" ]; then
    logerror
    logerror "NOTE: grid proxy is about to expire:"
    logerror "voms-proxy-info"
    voms-proxy-info --file=$proxy
    return 1
  fi

}

basename() {
  # This shell function is faster than calling /bin/basename 
  path=$1
  suffix=$2
  path=${path##*/}  # get everything after the final '/'
  if [ ! -z $suffix ]; then
    path=${path%$suffix}
  fi
  echo $path
}

printUsage() {
 echo "USAGE: `basename $0` [options]"
 echo ""
 echo "OPTIONS:"
 echo "   --srm-service=${SRM_SERVICE} (set SRM service URL)"
 echo "   --srm-base-path=${SRM_BASEPATH} (set the SRM basepath)"
 echo ""
 echo "NOTE: The name of the output file is set from the ntuple name!"
}

OPTS=`getopt -o "h" -l "help,srm-service:,srm-base-path:" -- "$@"`
if [ $? -ne 0 ]; then printUsage; fi
eval set -- "$OPTS"

while [ ! -z "$1" ]
do
  case "$1" in
    -h) printUsage; exit;;
    --help) printUsage; exit;;    
    --srm-service) shift; SRM_SERVICE=$1;;
    --srm-base-path) shift; SRM_BASEPATH=$1;;
    --) shift; break;;
    *) die "Unexpected option $1";;
  esac
  shift
done

if [ "$LNuAA_ANALYSIS_DIR" == "" ]; then
    logerror
    logerror "You have not initialized the LNuAA Analysis environment..."
    logerror "please do the following: \"source $CMSSW_BASE/src/LNuAA_Analysis/environment.sh"
    die
fi

if ! check_proxy $MIN_PROXY_HOURS $proxy ; then
  logerror
  logerror "Either rerun this command with --no-submit or create a new grid proxy"
  logerror "and rerun this command.  Example of how to create a grid proxy:"
  logerror
  logerror "voms-proxy-init --voms=cms --valid=48:00"
  die
fi

SRM_BASE="${SRM_SERVICE}${SRM_BASEPATH}"

TREE_DIR=

USER_DIRS="jkunkle"
TEMP="$@"
if [ "$TEMP" != "" ]; then  
  USER_DIRS=$@
fi

for user_dir in $USER_DIRS; do
  LCGDIR=$SRM_BASE/user/${user_dir}/${LNuAA_ANALYSIS_DIR}/${LNuAA_ANALYSIS_REVISION}  
  TEMP=`lcg-ls -bD srmv2 $LCGDIR | grep /job_`
  for a in $TEMP; do
    echo `basename $a`
  done  
done

